#!/bin/sh
# Copyright (C) 2016 evenS

install(){
    tar xzvf bing.tar.gz -C / 
    /etc/BingBackgroud/get_bing_cron.sh install
    /etc/BingBackgroud/get_bing_cron.sh cron
    ln -sf /tmp/bing.png /www/turbo-static/turbo/v2/img/bing.png
    sed -i '\#<link rel="stylesheet" type="text/css" href="<%=resource%>/v2/style/overbackgroud.css">#d' /usr/lib/lua/luci/view/admin_web/footer.htm
    sed -i '\#<link rel="stylesheet" type="text/css" href="<%=resource%>/v2/style/overbackgroud.css">#d' /usr/lib/lua/luci/view/admin_web/header.htm #兼容新版本黑色主题
    /etc/init.d/build_loginpage start
}

uninstall(){
    /etc/BingBackgroud/get_bing_cron.sh uninstall
    rm -rf /tmp/bing.png
    rm -rf /etc/BingBackgroud/
    rm -rf /www/turbo-static/turbo/v2/img/bing.png
    rm -rf /www/turbo-static/turbo/v2/js/bing.js
    if [ -f "/etc/market/GeeBlack.script" -a -f "/www/turbo-static/turbo/v2/style/overbackgroud.css" ]; then
        echo "<link rel=\"stylesheet\" type=\"text/css\" href=\"<%=resource%>/v2/style/overbackgroud.css\">" >> /usr/lib/lua/luci/view/admin_web/header.htm
    fi
    /etc/init.d/build_loginpage start
}